services:
  db:
    image: postgres
    container_name: "db"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ParkBuddy
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: "backend"
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ParkBuddy
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
